agent_configurations = [
    {
        "name": "Phytoplankton",
        "B": 25,
        "gamma": 0,
        "mu": 15,
        "rho": 0.683,
        "sigma": 0,
        "B_import": 700,
        "B_export": 0,
        "B_refuge": 0.250,
        "color": "#00ff00",
    },
    {
        "name": "Zooplankton",
        "B": 2,
        "gamma": 0.45,
        "mu": 12,
        "rho": 0.615,
        "sigma": 80,
        "B_import": 0,
        "B_export": 0,
        "B_refuge": 0.2,
        "color": "#ff0000",
    },
    {
        "name": "Anchovy",
        "B": 10.21,
        "gamma": 0.85,
        "mu": 1,
        "rho": 0.470,
        "sigma": 15.1,
        "B_import": 0,
        "B_export": 0,
        "B_refuge": 0.102,
        "color": "#0000ff",
    },
    {
        "name": "Sardine",
        "B": 10.59,
        "gamma": 0.5,
        "mu": 1,
        "rho": 0.405,
        "sigma": 6,
        "B_import": 0,
        "B_export": 0,
        "B_refuge": 0.105,
        "color": "#00ffff",
    },
    {
        "name": "Squid",
        "B": 0.7,
        "gamma": 0.85,
        "mu": 1,
        "rho": 0.531,
        "sigma": 4.7,
        "B_import": 0,
        "B_export": 0,
        "B_refuge": 0.001,
        "color": "#ff00ff",
    },
    {
        "name": "Hake",
        "B": 2,
        "gamma": 0.85,
        "mu": 1,
        "rho": 0.3,
        "sigma": 4.7,
        "B_import": 0,
        "B_export": 0,
        "B_refuge": 0.002,
        "color": "#ffff00",
    },
    {
        "name": "Birds",
        "B": 0.2,
        "gamma": 0.85,
        "mu": 10,
        "rho": 0.113,
        "sigma": 15.3,
        "B_import": 0,
        "B_export": 0,
        "B_refuge": 0.001,
        "color": "#ffa2a2",
    },
    {
        "name": "Seals",
        "B": 0.53,
        "gamma": 0.85,
        "mu": 8,
        "rho": 0.095,
        "sigma": 12.2,
        "B_import": 0,
        "B_export": 0,
        "B_refuge": 0.001,
        "color": "#a232a2",
    },
    {
        "name": "Whales",
        "B": 0.1,
        "gamma": 0.85,
        "mu": 9,
        "rho": 0.049,
        "sigma": 13.8,
        "B_import": 0,
        "B_export": 0,
        "B_refuge": 0.001,
        "color": "#7e00ff",
    },
]

foodweb_configuration = {
    "nodes": 9,
    "edges": [
        (0, 1),
        (0, 3),
        (1, 1),
        (1, 3),
        (1, 4),
        (1, 2),
        (1, 8),
        (2, 4),
        (2, 5),
        (2, 6),
        (2, 7),
        (3, 4),
        (3, 5),
        (3, 6),
        (3, 7),
        (4, 4),
        (4, 6),
        (5, 6),
        (5, 7),
    ],
}
